### ISSUE TITLE
Can not login with wings 1.3.1

### ISSUE THREAD

**Issue by Cmheidelberg** [KnowledgeCaptureAndDiscovery/wings-client#11]
**Describe the bug**
After updating to wings 1.3.1 my program was unable to login to the wings api. The login(password) function would return false. However, after reverting to 1.3.0 my program had no issues. 

**Expected behavior**

**Screenshots**
Here is my code my program was using to login to the api. The config.ini was not edited between versions.
![image](https://user-images.githubusercontent.com/14925268/62249349-0a91a580-b39f-11e9-8805-612ea9958723.png)

Here is the cmd output.
![image](https://user-images.githubusercontent.com/14925268/62249571-96a3cd00-b39f-11e9-8425-2e2b52209947.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809

**Comment by mosoriob** [comment]
The method init has changed (sorry for no documentation)
Here, there is a example working with the new version

I recommend you to use [hiighting code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) inside screenshot for code
```python
if __name__ == "__main__":
    wings_instance = wings.init()

    pattern = "economic"
    status = "SUCCESS"

    executions_resp = wings_instance.execution.list_executions_by_page(0, pattern, status).json()
    executions = executions_resp["rows"]
    logger.warning("{} executions matches with the pattern {}".format(len(executions), pattern
```

**Comment by Cmheidelberg** [comment]
Alright, thanks!

**Comment by mosoriob** [comment]
Did it work?

**Comment by mosoriob** [comment]
No feedback
