### ISSUE TITLE
When downloading a component, there is no way to retrieve sample data

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/wings-client#9]
**Describe the bug**
When I download a component, there is no option to download sample data. When I upload a component I have the option of specifying data. 

**To Reproduce**
The data fields of a YAML file cannot be completed with the information provided.

**Expected behavior**
There should be a sample data, taken from an existing execution for instance, that completed those fields and gave me the associated data and types.

**Comment by dgarijo** [comment]
This commit does not address the issue I opened. The commit addresses the issue of downloading the component code (which is great). This issue is regarding sample data to execute the component, if available. This is not urgent at the moment, but desirable.

**Comment by mosoriob** [comment]
I think this is an issue for the wings repo.

**Comment by dgarijo** [comment]
well, it describes something that I should be able to do through the client, isn't it?

**Comment by mosoriob** [comment]
Im not use. I dont know if wings provide a path/method.

**Comment by dgarijo** [comment]
Do you mean you are not sure? that's fine, we may have to open an issue in WINGS as you suggested.
This takes me to the issue that we should have an interface for adding and retrieving data easily from WINGS/client. But let's leave that for another moment.
